### ISSUE TITLE
crashes website after update

### ISSUE THREAD

**Issue by truesamurai** [getbowtied/shopkeeper-extender#6] opened 2020-07-21 15:05 UTC
Today I updated the Shopkeeper Extended plugin on a website with the latest WordPress version. But after the update the website crashed (error was: unexpected error) so I had to revert back to previous state.

**Comment by kitserve** [comment] 2020-07-27 09:35
Duplicate of #5. See there for a manual fix by editing the buggy file. Request @romi-getbowtied to push out the fix officially asap before more sites break!

**Comment by rthvanesa** [comment] 2020-07-27 10:45
Hello @sh1va73 ,

We are sorry for the inconvenience. We believe this error occurs only for Shopkeeper theme versions older than 2.8. However, we have applied a fix and released Shopkeeper Extender 1.6.3. 

Please let me know if you encounter any other issues. 

Have a good one!

**Closed as completed** 2020-07-27 10:45 UTC
