### ISSUE TITLE
Conflict with Yoast SEO and ACF causes blank Yoast meta box

### ISSUE THREAD

**Issue by monbauza** [getbowtied/shopkeeper-extender#1] opened 2019-01-29 08:04 UTC
When the Advanced Custom Fields plugin and the Shopkeeper Extender plugins are active, the Yoast meta box appears blank on WooCommerce product pages. Disabling ACF or Shopkeeper Extender resolves the conflict.

Please, refer to the Yoast SEO repo for more information: https://github.com/Yoast/wordpress-seo/issues/12116

**Comment by adrianlbs** [comment] 2019-01-30 12:57
Hi @monbauza , thanks for reaching out!
I've just assigned this issue to @rthvanesa, she will be looking into it for the following update.

Thank you for using Shopkeeper!

Cheers,
Adrian.

**Comment by mattmintun** [comment] 2019-01-30 23:07
subscribed - same is happening with me.

**Comment by rthvanesa** [comment] 2019-02-05 11:36
Hi! Thank you for reporting this issue. 

I've looked deeper into this and there was indeed a compatibility issue caused by a javascript file that should've been enqueued only in the block editor page. 
I have fixed this in the newest release, [version 1.3.3](https://github.com/getbowtied/shopkeeper-extender/releases/tag/v.1.3.3).

Please update the plugin and get back to us in case the issue is still there.

Have a good one!
Vanesa

**Closed as completed** 2019-02-05 11:37 UTC
Labels: bug, fixed

**Comment by mattmintun** [comment] 2019-02-05 16:17
Hey Vanesa, what JS file was it that was causing the issue if you don't mind me asking

**Comment by rthvanesa** [comment] 2019-02-07 09:24
It's the includes/gbt-blocks/assets/js/main.js file that should have been enqueued in the block editor assets. It creates the block category 'Shopkeeper Blocks' under which you can find our blocks.
